version: "3"
services:
    webserver:
        build: .
        container_name: apache-php
        volumes:
            - ./projects:/var/www/html
            - /etc/timezone:/etc/timezone
        ports:
            - "80:80"
        depends_on:
            - postgres
            - mysql
        restart: always

    postgres:
        image: postgres:13
        container_name: postgres13
        volumes:
            - ./database/postgresql:/var/lib/postgresql/data
            - /etc/timezone:/etc/timezone
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        restart: always

    mysql:
        image: mysql:5.7
        container_name: mysqldb
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./database/mysql:/var/lib/mysql57
            - /etc/timezone:/etc/timezone
        networks:
            - default
        restart: always
